eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://${eureka.node1.name}:${eureka.node1.port}/eureka/

  node1:
    name: shop-server
    port: 8761