spring:
  profiles:
    active: jdbc
  cloud:
    config:
      server:
        jdbc:
          sql: select app_key, app_value from t_config where service_id = ? and profile = ? and label = ?
  application:
    name: shop-configuration
server:
  port: 8889

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
